# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/shift/axolotl/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/shift/axolotl

PRODUCT_COPY_FILES += \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/ath10k/WCN3990/hw1.0/board-2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ath10k/WCN3990/hw1.0/board-2.bin \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/ath10k/WCN3990/hw1.0/firmware-5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ath10k/WCN3990/hw1.0/firmware-5.bin \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qca/axolotl/crnv21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/qca/axolotl/crnv21.bin \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qca/crbtfw21.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/qca/crbtfw21.tlv \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/a630_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/a630_gmu.bin \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/a630_sqe.fw \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/a630_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/a630_zap.mbn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/adsp.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/adsp.mbn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/adspr.jsn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/adspr.jsn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/adspua.jsn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/adspua.jsn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/cdsp.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/cdsp.mbn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/cdspr.jsn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/cdspr.jsn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/ipa_fws.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/ipa_fws.mbn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/mba.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/mba.mbn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/modem.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/modem.mbn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/modemr.jsn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/modemr.jsn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/modemuw.jsn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/modemuw.jsn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/slpi.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/slpi.mbn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/slpir.jsn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/slpir.jsn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/slpius.jsn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/slpius.jsn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/venus.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/venus.mbn \
    vendor/shift/proprietary/axolotl/proprietary/vendor/firmware/qcom/sdm845/axolotl/wlanmdsp.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/qcom/sdm845/axolotl/wlanmdsp.mbn
